### ISSUE TITLE
repository org change broke Javadoc hosting

### ISSUE THREAD

**Issue by SethTisue** [lightbend/config#530] opened 2017-11-16 21:26 UTC
reported by @ben-manes at https://github.com/lightbend/config/issues/509#issuecomment-340578300

 @havocp is it worth rolling a new release to fix those links?

**Comment by havocp** [comment] 2017-11-16 22:05
I'd be fine with a release for this if someone can take it on, but not sure when I could get to it myself :-/

**Comment by ktoso** [comment] 2017-11-17 00:56
We'll get to it 👍

**Comment by dwijnand** [comment] 2018-02-22 08:24
Duplicate of #516

**Closed by dwijnand** 2018-02-22 08:24 UTC
